### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by anonymousandrew** [grow/pygrow#143]
Trying to update grow. Is this user error? :(

$ curl https://install.growsdk.org | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   377  100   377    0     0   1221      0 --:--:-- --:--:-- --:--:--  1224
Traceback (most recent call last):
  File "/var/folders/00/1j02r000h01000cxqpysvccm00640b/T/tmp.XXXXXXXXXX.P04TZHMz/install_growsdk.py", line 169, in <module>
    main()
  File "/var/folders/00/1j02r000h01000cxqpysvccm00640b/T/tmp.XXXXXXXXXX.P04TZHMz/install_growsdk.py", line 165, in main
    install(rc_path=args.rc_path, bin_path=args.bin_path, force=args.force)
  File "/var/folders/00/1j02r000h01000cxqpysvccm00640b/T/tmp.XXXXXXXXXX.P04TZHMz/install_growsdk.py", line 69, in install
    release = json.loads(urllib.urlopen(RELEASES_API).read())[0]
KeyError: 0

**Comment by jeremydw** [comment]
I'm almost certain this is happening because GitHub is rate limiting requests from your IP. We should probably handle this case and fail more gracefully.
