### ISSUE TITLE
grow binary tracebacks show build system path

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#45]
Tracebacks displayed by the `grow` binary currently show the build system's path. Example below. The issue actually has to do with PyInstaller and the code freezing process. There is apparently a workaround that we can look into (see links below), but it seems no one is actively working on this issue on the PyInstaller side.

- PyInstaller ticket: http://www.pyinstaller.org/ticket/154
- Brief additional discussion: https://groups.google.com/forum/#!msg/pyinstaller/5moN79yD8Ag/MQ4Z1bdU5u8J

```
stevenle@sl-ubuntu:~/src/stevenle.github.io$ grow run _grow

Traceback (most recent call last):
  File "<string>", line 34, in <module>
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/google_apputils.appcommands", line 796, in Run
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/google_apputils.app", line 238, in run
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/google_apputils.app", line 267, in _actual_start
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/google_apputils.appcommands", line 793, in InterceptReallyStart
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/google_apputils.app", line 220, in really_start
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/google_apputils.appcommands", line 778, in _CommandsStart
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/google_apputils.appcommands", line 284, in CommandRun
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/grow.commands", line 186, in Run
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/grow.server.manager", line 53, in start
AttributeError: 'module' object has no attribute 'create_dev_server_observer'
```

**Comment by jeremydw** [comment]
Updated on PyInstaller's GitHub: https://github.com/pyinstaller/pyinstaller/issues/1059
