### ISSUE TITLE
`context` is undefined using `grow machine_translate`.

### ISSUE THREAD

**Issue by stevenle** [grow/pygrow#59]
Traceback:

```
$ grow machine_translate --locale=es .                                                                                    
[13:11:50] Updating translation template: /translations/messages.pot
[13:11:50] Extracting from: /views/base.html
[13:11:50] Extracting from: /content/pages/index.html
[13:11:50] Extracting from collection: /content/pages
Traceback (most recent call last):
  File "/usr/local/bin/grow", line 5, in <module>
    pkg_resources.run_script('grow==0.0.39', 'grow')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/grow-0.0.39-py2.7.egg/EGG-INFO/scripts/grow", line 37, in <module>
    grow()
  File "/Library/Python/2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/grow-0.0.39-py2.7.egg/grow/commands/machine_translate.py", line 15, in machine_translate
    pod.catalogs.extract()
  File "/Library/Python/2.7/site-packages/grow-0.0.39-py2.7.egg/grow/pods/catalogs/catalog_holder.py", line 137, in extract
    utils.walk(doc.tagged_fields, lambda *args: callback(doc, *args))
  File "/Library/Python/2.7/site-packages/grow-0.0.39-py2.7.egg/grow/common/utils.py", line 61, in walk
    callback(item, key, node)
  File "/Library/Python/2.7/site-packages/grow-0.0.39-py2.7.egg/grow/pods/catalogs/catalog_holder.py", line 137, in <lambda>
    utils.walk(doc.tagged_fields, lambda *args: callback(doc, *args))
  File "/Library/Python/2.7/site-packages/grow-0.0.39-py2.7.egg/grow/pods/catalogs/catalog_holder.py", line 123, in callback
    _handle_field(doc.pod_path, item, key, unused_node)
  File "/Library/Python/2.7/site-packages/grow-0.0.39-py2.7.egg/grow/pods/catalogs/catalog_holder.py", line 130, in _handle_field
    item, None, [(path, 0)], auto_comments=comments, context=context)
NameError: free variable 'context' referenced before assignment in enclosing scope
```

LOC:
https://github.com/grow/pygrow/blob/develop/grow/pods/catalogs/catalog_holder.py#L130

**Comment by jeremydw** [comment]
Will fix this up and add a test. Do you have/remember the YAML structure that caused the problem so I can cover it in the test?

**Comment by stevenle** [comment]
It was pretty minimal:

podspec.yaml:
```yaml
static_dirs:
- static_dir: /static/
  serve_at: /static

localization:
  default_locale: en
  locales:
  - en
  - es

preprocessors:
- kind: sass
  sass_dir: /source/sass/
  out_dir: /static/css/
  output_style: compressed

deployments:
```

_blueprint.yaml:
```yaml
path: /
view: /views/base.html
localization:
  path: /{locale}/
```

**Comment by jeremydw** [comment]
Were there any content files / YAML front matter with tagged strings that were being extracted?
