### ISSUE TITLE
Improve support for serving large files (>2MB) on the development server

### ISSUE THREAD

**Issue by jeremydw** [grow/pygrow#60]

**Comment by matthewhall** [comment]
Traceback (most recent call last):
  File "growsdk/wsgiref.handlers", line 86, in run
  File "growsdk/wsgiref.handlers", line 128, in finish_response
  File "growsdk/wsgiref.handlers", line 217, in write
  File "growsdk/socket", line 324, in write
  File "growsdk/socket", line 303, in flush
error: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49995)
Traceback (most recent call last):
  File "growsdk/SocketServer", line 295, in _handle_request_noblock
  File "growsdk/SocketServer", line 321, in process_request
  File "growsdk/SocketServer", line 334, in finish_request
  File "growsdk/SocketServer", line 651, in __init__
  File "growsdk/SocketServer", line 710, in finish
  File "growsdk/socket", line 279, in close
  File "growsdk/socket", line 303, in flush
error: [Errno 32] Broken pipe
----------------------------------------

**Comment by WillsB3** [comment]
Just to note this here as it's related: The development server also doesn't seem to support streaming requests so serving HTML5 video locally doesn't work well (e.g. the seeking and the loop attribute doesn't work correctly).
