### ISSUE TITLE
machine_translate error

### ISSUE THREAD

**Issue by Willis77** [grow/pygrow#69]
I'm loving the overall idea of GrowSDK and having fun exploring it. But I have run into the following glitch on Linux with 0.0.44.

When running, for example:

```
grow machine_translate --locale=ja ./my-codelab/
```

I get the following result:

```
[08:59:11] Updating translation template: /translations/messages.pot
[08:59:11] Extracting from: /views/index.html
[08:59:11] Extracting from: /views/base.html
[08:59:11] Extracting from: /views/posts.html
[08:59:11] Extracting from: /views/team.html
[08:59:11] Extracting from: /views/pages.html
[08:59:11] Extracting from: /views/archive.html
[08:59:11] Extracting from: /views/errors/default.html
[08:59:11] Extracting from collection: /content/pages
[08:59:11] Extracting from collection: /content/posts
[08:59:11] Extracting from podspec: /podspec.yaml
[08:59:11] Writing 33 messages to translation template.
Traceback (most recent call last):
  File "<string>", line 43, in <module>
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/click.core", line 610, in __call__
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/click.core", line 590, in main
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/click.core", line 936, in invoke
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/click.core", line 782, in invoke
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/click.core", line 416, in invoke
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/grow.commands.machine_translate", line 19, in machine_translate
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/grow.pods.catalogs.catalogs", line 192, in machine_translate
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/goslate", line 166, in _execute
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/goslate", line 363, in <lambda>
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/goslate", line 283, in _translate_single_text
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/goslate", line 166, in _execute
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/goslate", line 281, in <lambda>
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/goslate", line 206, in _basic_translate
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/goslate", line 144, in _open_url
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 410, in open
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 523, in http_response
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 442, in error
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 382, in _call_chain
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 629, in http_error_302
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 410, in open
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 523, in http_response
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 448, in error
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 382, in _call_chain
  File "/home/jeremydw/git/pygrow/build/grow/out00-PYZ.pyz/urllib2", line 531, in http_error_default
urllib2.HTTPError: HTTP Error 400: Bad Request
```

**Comment by jeremydw** [comment]
Hi! I can reproduce this too. Looks like there's either an issue with the `goslate` translation library we're using, Google Translate, or some integration of the two.

Here's a traceback of a test case that doesn't involve Grow at all:

```
>>> import goslate
>>> gs = goslate.Goslate()
>>> print gs.translate('hello world', 'de')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremydw/Library/Python/2.7/lib/python/site-packages/goslate-1.1.2-py2.7.egg/goslate.py", line 338, in translate
    return self._translate_single_text(text, target_language, source_language)
  File "/Users/jeremydw/Library/Python/2.7/lib/python/site-packages/goslate-1.1.2-py2.7.egg/goslate.py", line 283, in _translate_single_text
    return ''.join(self._execute(make_task(i) for i in split_text(text)))
  File "/Users/jeremydw/Library/Python/2.7/lib/python/site-packages/goslate-1.1.2-py2.7.egg/goslate.py", line 166, in _execute
    yield each()
  File "/Users/jeremydw/Library/Python/2.7/lib/python/site-packages/goslate-1.1.2-py2.7.egg/goslate.py", line 281, in <lambda>
    return lambda: self._basic_translate(text, target_language, source_lauguage)[0]
  File "/Users/jeremydw/Library/Python/2.7/lib/python/site-packages/goslate-1.1.2-py2.7.egg/goslate.py", line 206, in _basic_translate
    response_content = self._open_url(url)
  File "/Users/jeremydw/Library/Python/2.7/lib/python/site-packages/goslate-1.1.2-py2.7.egg/goslate.py", line 154, in _open_url
    raise e
socket.timeout: timed out
```

**Comment by jeremydw** [comment]
According to https://cloud.google.com/translate/v2/faq there is no longer any free tier for the Google Translate API. Interestingly enough I just used the machine translate feature a few weeks ago, so perhaps it was a recent change.

We'll have to see if there's a workaround – or perhaps add the ability for Grow to use your API key so you can pay for the Translate service if needed.

**Comment by Willis77** [comment]
Perhaps some sort of hybrid approach would be the most flexible solution. In some quick searching, I have not yet turned up a straight replacement and most of the services I found also require API keys.

This post has links to several services, not all equally relevant.

https://www.quora.com/Are-there-any-good-open-source-collaborative-translation-apps

**Comment by jeremydw** [comment]
I was still able to reproduce the issue and upgrading goslate fixed it (per https://bitbucket.org/zhuoqiang/goslate/) – we'll cut a new release of grow that integrates this fix tomorrow!
