### ISSUE TITLE
Invalid requirement specification error

### ISSUE THREAD

**Issue by uxder** [grow/pygrow#89]
After installing the grow sdk, I'm trying to run the codelab and getting an error, when running `grow run` or `grow build`.

```
ValueError: Invalid requirement specification: u'0.0.26'
```

I'm suspecting that the grow_version declared in podspec.yaml of the codelab (which happens to be 0.0.26) is outdated?

Here is the full output.
```
██ @Tomoharus-MacBook-Pro  ~/Desktop/code/experiments$  mkdir grow-codelab

██ @Tomoharus-MacBook-Pro  ~/Desktop/code/experiments$  grow init codelab grow-codelab
Initializing with https://github.com/growthemes/codelab.git...
Pod ready to go: /Users/tomoharuyano/Desktop/code/experiments/grow-codelab

██ @Tomoharus-MacBook-Pro  ~/Desktop/code/experiments$  ls ./grow-codelab
content		podspec.yaml	source		static		translations	views

██ @Tomoharus-MacBook-Pro  ~/Desktop/code/experiments$  grow run grow-codelab
Traceback (most recent call last):
  File "<string>", line 55, in <module>
  File "growsdk/click.core", line 664, in __call__
  File "growsdk/click.core", line 644, in main
  File "growsdk/click.core", line 991, in invoke
  File "growsdk/click.core", line 837, in invoke
  File "growsdk/click.core", line 464, in invoke
  File "growsdk/grow.commands.run", line 31, in run
  File "growsdk/grow.pods.pods", line 94, in __init__
  File "growsdk/grow.common.sdk_utils", line 45, in check_sdk_version
  File "growsdk/semantic_version.base", line 460, in __init__
  File "growsdk/semantic_version.base", line 466, in parse
  File "growsdk/semantic_version.base", line 466, in <genexpr>
  File "growsdk/semantic_version.base", line 404, in __init__
  File "growsdk/semantic_version.base", line 419, in parse
ValueError: Invalid requirement specification: u'0.0.26'

██ @Tomoharus-MacBook-Pro  ~/Desktop/code/experiments$  grow build grow-codelab
Traceback (most recent call last):
  File "<string>", line 55, in <module>
  File "growsdk/click.core", line 664, in __call__
  File "growsdk/click.core", line 644, in main
  File "growsdk/click.core", line 991, in invoke
  File "growsdk/click.core", line 837, in invoke
  File "growsdk/click.core", line 464, in invoke
  File "growsdk/grow.commands.build", line 19, in build
  File "growsdk/grow.pods.pods", line 94, in __init__
  File "growsdk/grow.common.sdk_utils", line 45, in check_sdk_version
  File "growsdk/semantic_version.base", line 460, in __init__
  File "growsdk/semantic_version.base", line 466, in parse
  File "growsdk/semantic_version.base", line 466, in <genexpr>
  File "growsdk/semantic_version.base", line 404, in __init__
  File "growsdk/semantic_version.base", line 419, in parse
ValueError: Invalid requirement specification: u'0.0.26'
```

**Comment by uxder** [comment]
Well, removing the line:

`grow_version: 0.0.50`

from podspec.yaml in the codelab did the trick.  I suppose the codelab probably just needs to be updated.

**Comment by jeremydw** [comment]
Ah, we do definitely need to update the codelab. That syntax should be updated to: `grow_version: ">=0.0.5"` – for semantic versioning. Thanks for catching that!

**Comment by jeremydw** [comment]
We updated all the repos in `growthemes`. Should be good to go now!
